### ISSUE TITLE
Move music-app folder contents to root

### ISSUE THREAD

**Issue by berniedurfee** [Lambda-School-Labs/Music-Meteorologist-fe#3]
It looks like create react app was run from the root folder, instead of creating the root folder using CRA. This makes the repo sort of a mono-repo, but not really.

Best to fix this by moving the contents of the `music-app` folder down a level, to the root and then deleting the now empty `music-app` folder.

**Comment by erik-sandoval** [comment]
Hey Bernie, thanks for that. I just moved it to root 👍
