### ISSUE TITLE
Clicking on item in playlist does not pull up the item in the player

### ISSUE THREAD

**Issue by zwarshavsky** [Lambda-School-Labs/Music-Meteorologist-fe#36]
See screenshot:

https://screencast.com/t/FFC19kXDtN0

**Comment by xander-bennett** [comment]
Tested to confirm. Confirmed issue

**Comment by AMC-ai** [comment]
again please try sound-drip.com and see if the problem persist as that is the most updated code | we will look into it further as well, ty.

**Comment by AMC-ai** [comment]
we have checked this have found the current code to not have this issue. ty.
