### ISSUE TITLE
On initial load, page appears broken

### ISSUE THREAD

**Issue by zwarshavsky** [Lambda-School-Labs/Music-Meteorologist-fe#37]
See screenshot:

https://screencast.com/t/xa1ctiegNV

Possible solution would be to keep loading animation screen on longer before page is fully ready

**Comment by AMC-ai** [comment]
please try sound-drip.com and see if the problem persist as that is the most updated code and that issue for me no longer persists. ty.

**Comment by AMC-ai** [comment]
we don't consider this to be a bug as this is the loader page, that being said the loader page can be polished. But as far as the functionality that was expressed there would need to be a rework of the state the app is fully built around, changing it could possible add more bugs, it being so close to time we may want to wait to implement this new state. 

also this has been added to the notion docs as a new user functionality.
