### ISSUE TITLE
On initial load, the song in the player does not match the first song in the playlist

### ISSUE THREAD

**Issue by zwarshavsky** [Lambda-School-Labs/Music-Meteorologist-fe#38]
See screenshot:

https://screencast.com/t/kMSbwEE5

**Comment by AMC-ai** [comment]
defiantly something to look into, my understanding is our app is considered a device that Spotify plays on so which ever song you had last playing will load in the player.

**Comment by AMC-ai** [comment]
We also consider this not to be a bug, but a new user functionality as this has never been a functionality in the code and would need to be newly implemented. We have documented this in the notion docs for the next team to implement it if we are unable to do so ourselves, ty.
