### ISSUE TITLE
Clicking play on playlist item does not auto play the track in the player

### ISSUE THREAD

**Issue by zwarshavsky** [Lambda-School-Labs/Music-Meteorologist-fe#39]
See screenshot: https://screencast.com/t/ESSv2YVo

**Comment by AMC-ai** [comment]
unless I misunderstand, it should and plays from the playlist when I press play. I would also like to note only individual songs play, the track of all 20 songs will not automatically play (each song has to be played). Will look into further, ty.

**Comment by AMC-ai** [comment]
We consider this not to be a bug but a new user functionality as this has never been a functionality in the code and would need to be newly implemented. We have documented this in the notion docs for the next team implement if we are unable to do so ourselves, ty.
